### ISSUE TITLE
Procurement div margin-right missing

### ISSUE THREAD

**Issue by emekler0729** [emekler0729/ae-database#1]
There is no margin between the procurement block and the right side of the page like there is with the product block and left side of the page.

**Comment by emekler0729** [comment]
@EnzoMartin can you take a look at this? Latest version should be on the gh-pages.

**Comment by EnzoMartin** [comment]
![image](https://user-images.githubusercontent.com/735558/39227717-73d06c90-485a-11e8-88d5-f3d5a5c6c263.png)

The right column (red) is set on the bootstrap column, whereas in the left (orange) it's a sub div, you need to create a new div with the `procurement` id inside of the div that has `col-sm-4`

**Comment by emekler0729** [comment]
Got it! Thanks!
